[master] Remove docker installation
rancher/machine pull request #109
Opened 2021-01-11 18:47 UTC by PennyScissors

Issue: https://github.com/rancher/rancher/issues/27646

As discussed, removed the docker installation step during provision. The expectation now is the user has already pre-installed everything they need to have installed docker themselves (will need to be documented).

2021-01-12 07:15 UTC, superseb requested changes
I think there is a interpretation issue on the issue comment, the solution is to have a possibility to skip: ```basics here should be a skip provision for the create command which will bypass all provisioning and docker installation. ```

If we default to not provisioning, we will break all new node driver machines.

2021-01-12 08:17 UTC, vincent99 commented
I agree, this seems like it should be an opt-in option to the provisioner, or a different provisioner altogether (this is rancheros nodes skip installing Docker).

Almost all usage of almost all drivers produces an machine that still needs Docker installed on it (at least until doing rke2 provisioning).

If nothing else, we still have to maintain this for 2.5.x/2.4/2.3 for a long time.. the behavior certainly can't majorly change for those, so just dropping it would require we start maintaining two branches.

2021-01-19 15:36 UTC, superseb reviewed
I assume this is tested via the UI? So there is no input verification for an URL in this field?

2021-01-19 17:23 UTC, PennyScissors commented
@superseb Yes, tested in the UI, all scenarios I listed work as expected.

2021-01-19 19:52 UTC, superseb submitted a review, later dismissed

2021-01-21 00:21 UTC, luthermonson commented on libmachine/provision/debian.go
> +	if strings.EqualFold(engineOptions.InstallURL, "none") {
removing the yum update you can put this in installDockerGeneric and have one check

2021-01-21 17:56 UTC, luthermonson commented on libmachine/provision/utils.go
> +	log.Info("Installing Docker")
maybe nice to put the baseURL in the log msg?

2021-01-21 18:10 UTC, luthermonson approved these changes

2021-01-21 18:11 UTC, merged