update default storage driver to overlay2 for suse os
rancher/machine pull request #232
Opened 2023-10-25 11:34 UTC by vardhaman22

issue: https://github.com/rancher/rancher/issues/43254
overlay storage driver is removed in docker v24.0 [ref](https://docs.docker.com/engine/deprecated/#:~:text=Legacy%20overlay%20storage%20driver&text=The%20overlay%20storage%20driver%20is,0.)

2023-12-08 16:36 UTC, jiaqiluo requested changes
Question:
Do we hit this issue if we use another OS with docker v24.0? And how is it handled for other OS?

2023-12-11 16:53 UTC, vardhaman22 commented
> Question: Do we hit this issue if we use another OS with docker v24.0? And how is it handled for other OS?

the default storage driver was updated in this PR: https://github.com/rancher/machine/pull/92 but i guess suse was not updated in this for some reason

2023-12-12 04:36 UTC, kinarashah approved these changes

2023-12-12 18:00 UTC, jiaqiluo approved these changes
@vardhaman22 , I do not find any clue from the original PR and linked issues for the reason, but I also do not see any reason to prevent you from fixing it now.  

I think the issue also exists in Rancher v2.7.x because it is from rancher-machine.  Did you get it reproduced in v2.7.x, or can you give it a try to confirm? 

I think we may need to backport the fix to Rancher v2.7.x,  it basically means you need to create a backport issue in GH.

2023-12-14 12:11 UTC, vardhaman22 commented
> @vardhaman22 , I do not find any clue from the original PR and linked issues for the reason, but I also do not see any reason to prevent you from fixing it now.
> 
> I think the issue also exists in Rancher v2.7.x because it is from rancher-machine. Did you get it reproduced in v2.7.x, or can you give it a try to confirm?
> 
> I think we may need to backport the fix to Rancher v2.7.x, it basically means you need to create a backport issue in GH.

sure i will try with v2.7.x and create a backport issue.

2023-12-14 12:11 UTC, merged